global_frame: lidar_odom
rolling_window: true
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 5.0
transform_tolerance: 10.0
resolution: 0.05
# footprint: [[-0.2, 0.4], [1.2, 0.4], [1.4, 0.0], [1.2, -0.4], [-0.2, -0.4]]
# footprint_padding: 0.05
always_send_full_costmap: false

plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: camera_f_laser camera_r_laser
  camera_f_laser:
    sensor_frame: camera_f_mount_link 
    data_type: LaserScan
    clearing: true
    marking: true
    topic: /camera_f/scan
    inf_is_valid: false
    obstacle_range: 5.5
    raytrace_range: 6.0
  camera_r_laser: 
    sensor_frame: camera_r_mount_link
    data_type: LaserScan
    clearing: true
    marking: true
    topic: /camera_r/scan
    inf_is_valid: false
    obstacle_range: 5.5
    raytrace_range: 6.0

inflation:
  inflation_radius: 1.0