global_frame: lidar_odom
rolling_window: true
track_unknown_space: true
robot_base_frame: base_link
update_frequency: 3.0
publish_frequency: 3.0
transform_tolerance: 10.0
resolution: 0.05
# footprint: [[-0.2, 0.4], [1.2, 0.4], [1.4, 0.0], [1.2, -0.4], [-0.2, -0.4]]
# footprint_padding: 0.05

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

obstacles_laser:
  observation_sources: lidar
  lidar: 
    data_type: PointCloud2
    clearing: true
    marking: true
    topic: /velodyne_points
    # inf_is_valid: true
    min_obstacle_height: 0.5
    max_obstacle_height: 2.5
    obstacle_range: 30.0
    raytrace_range: 35.0


inflation:
  inflation_radius: 1.0