# for visual odometry and imu fusion

frequency: 10
sensor_timeout: 1.0
two_d_mode: true
transform_time_offset: 0.0
transform_time_out: 0.0
print_diagnostics: true
publish_tf: true
publish_acceleration: false

world_frame: wodom
# map_frame: map
odom_frame: wodom
base_link_frame: base_link

#odom0: visual odometry
odom0: wheel_odom
odom0_config: [true, true, false,
               false, false, false,
               true, false, false,
               false, false, true,
               false, false, false]
odom0_differential: true
odom0_relative: true

#imu0: imu data
imu0: imu_data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              false, false, true,
              false, false, false]
imu0_differential: false
imu0_relative: false