# for visual odometry and imu fusion

frequency: 10
sensor_timeout: 1.0
two_d_mode: true
transform_time_offset: 0.0
transform_time_out: 0.0
print_diagnostics: true
publish_tf: true
publish_acceleration: false

world_frame: wodom
# map_frame: map
odom_frame: wodom
base_link_frame: base_link

#odom0: visual odometry
odom0: wheel_odom
odom0_config:
  [
    true,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
  ]
# [ADVANCED] When measuring one pose variable with two sensors, a situation can arise in which both sensors under-
# report their covariances. This can lead to the filter rapidly jumping back and forth between each measurement as they
# arrive. In these cases, it often makes sense to (a) correct the measurement covariances, or (b) if velocity is also
# measured by one of the sensors, let one sensor measure pose, and the other velocity. However, doing (a) or (b) isn't
# always feasible, and so we expose the differential parameter. When differential mode is enabled, all absolute pose
# data is converted to velocity data by differentiating the absolute pose measurements. These velocities are then
# integrated as usual. NOTE: this only applies to sensors that provide pose measurements; setting differential to true
# for twist measurements has no effect.
odom0_differential: true
# [ADVANCED] When the node starts, if this parameter is true, then the first measurement is treated as a "zero point"
# for all future measurements. While you can achieve the same effect with the differential paremeter, the key
# difference is that the relative parameter doesn't cause the measurement to be converted to a velocity before
# integrating it. If you simply want your measurements to start at 0 for a given sensor, set this to true.
odom0_relative: false
# We should set to true either odom0_differential or odom0_relative, not both !
# Setting both to true is equivalent to setting only odom0_differential to true.

#imu0: imu data
imu0: imu_data
imu0_config:
  [
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
  ]
imu0_differential: false
imu0_relative: false
