<?xml version="1.0"?>


<!-- Based on ackermann_1.urdf in simple_ackermann repository:
https://github.com/benwarrick/simple_ackermann.git -->


<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="soma">

	<!-- Include files -->
	<include filename="$(find soma_description)/urdf/utils.xacro" />
	<include filename="$(find soma_description)/urdf/front_steer_macro.xacro" />
	<include filename="$(find soma_description)/urdf/front_wheel_macro.xacro" />
	<include filename="$(find soma_description)/urdf/rear_wheel_macro.xacro" />
	<include filename="$(find soma_description)/urdf/virtual_rear_wheel_macro.xacro" />


	<!-- Ackermann macro -->
	<macro name="ackermann_macro" params="parent">

		<!-- General properties used for inertia computation -->
		<property name="mass" value="250" />
		<property name="width" value="1.05" />
		<property name="depth" value="0.70" />
		<property name="height" value="1.7" />

		<!-- Bottom body joint -->
		<joint name="body_bottom_joint" type="fixed">
			<parent link="${parent}" />
			<child link="body_bottom_link" />
			<origin xyz="0 0 ${0.2286 + 0.5/4}" rpy="0.0 0.0 0.0" />
		</joint>

		<!-- Bottom body link -->
		<link name="body_bottom_link">

			<!-- Inertial part -->
			<inertial>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
				<mass value="${0.8*mass}" />

				<!-- Inertia matrix of a parallelepiped -->
				<parallelepiped_inertia mass="${0.8*mass}" width="${width}" height="0.5" depth="${depth}" />
				<!-- Old values: ixx = iyy = izz = 0.001 -->
			</inertial>

			<!-- Visual part -->
			<visual>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
				<geometry>
					<box size="${width} ${depth} 0.5" />
				</geometry>
				<material name="gray" />
			</visual>

			<!-- Collision part -->
			<collision>
				<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
				<geometry>
					<box size="${width} ${depth} 0.5" />
				</geometry>
			</collision>

		</link>
		<!-- END bottom body link -->

		<!-- Gazebo additional parameters -->
		<gazebo reference="body_bottom_link">
			<material>
				Gazebo/Gray
			</material>
		</gazebo>




		<!-- Build links and joints for ackermann_steering_controller -->
		<front_steer_macro parent="body_bottom_link" prefix="ackermann" xyz="${width/2 - 0.1} 0 ${-0.5/4}" />
		<virtual_rear_wheel_macro parent="body_bottom_link" prefix="ackermann" xyz="${-width/2 + 0.1} 0 ${-0.5/4}" />

		<!-- Build wheels -->
		<front_wheel_macro parent="body_bottom_link" prefix="left" xyz="${width/2 - 0.1} ${depth/2 + 0.0889} ${-0.5/4}" />
		<front_wheel_macro parent="body_bottom_link" prefix="right" xyz="${width/2 - 0.1} ${-depth/2 - 0.0889} ${-0.5/4}" />
		<rear_wheel_macro parent="body_bottom_link" prefix="left" xyz="${-width/2 + 0.1} ${depth/2 + 0.0889} ${-0.5/4}" />
		<rear_wheel_macro parent="body_bottom_link" prefix="right" xyz="${-width/2 + 0.1} ${-depth/2 - 0.0889} ${-0.5/4}" />

	</macro>

</robot> 
