diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ["left_front_wheel_rotate", "left_rear_wheel_rotate"]
  right_wheel: ["right_front_wheel_rotate", "right_rear_wheel_rotate"]

  publish_rate: 20.0
  cmd_vel_timeout: 1.0
  wheel_separation: 0.8778 # 0.70 (body depth) + 2 * 0.0889 (wheel length)
  wheel_radius: 0.2286
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

  # tf
  enable_odom_tf: false
  base_frame_id: base_link
  odom_frame_id: odom

  # limits
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 0.55 # m/s
      min_velocity: -0.55 # m/s
      has_acceleration_limits: true
      max_acceleration: 1.0 # m/s^2
      min_acceleration: -1.0 # m/s^2
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 1.5 # rad/s
      min_velocity: -1.5 # rad/s
      has_acceleration_limits: true
      max_acceleration: 1.0 # rad/s^2
      min_acceleration: -1.0 # rad/s^2
