footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    # map_topic: /map
    map_topic: /rtabmap/rtabmap/grid_map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: point_cloud_sensor
    point_cloud_sensor: {data_type: PointCloud2, expected_update_rate: 1, clearing: true, marking: true, topic: /rtabmap/rtabmap/local_grid_obstacle, min_obstacle_height: -99999.0,
    max_obstacle_height: 99999.0}

inflation:
    inflation_radius: 1.0

