# for visual odometry and imu fusion

frequency: 10
sensor_timeout: 1.0
two_d_mode: true
transform_time_offset: 0.0
transform_time_out: 0.0
print_diagnostics: true
publish_tf: true
publish_acceleration: false

world_frame: m_odom
map_frame: m_map
odom_frame: m_odom
base_link_frame: base_link

#odom0: wheel odometry
odom0: odom0
odom0_config: [true, true, false,
               false, false, true,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_relative: true               
odom0_queue_size: 2       
odom0_nodelay:  false  
odom0_pose_rejection_threshold: 5
odom0_twist_rejection_threshold: 1

#gps
odom1: odom1
odom1_config: [true, true, false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom1_differential: false
odom1_relative: false
odom1_queue_size: 2       
odom1_nodelay:  false  
odom1_pose_rejection_threshold: 2
odom1_twist_rejection_threshold: 0.2

#imu0: imu data
imu0: imu_data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, false,
              false, false, false]
imu0_differential: false
imu0_relative: true
imu0_queue_size: 5   
imu0_nodelay:  false  
imu0_pose_rejection_threshold: 0.8
imu0_twist_rejection_threshold: 0.8
imu0_linear_acceleration_rejection_threshold: 0.8
imu0_remove_gravitational_acceleration: true

# use control: true
# stamped_control: false
# control_timeout: 0.2
# control_config : [true,false,false,false,false,true]
# acceleration_limits : [1.3,0.0,0.0,0.0,0.0,3.4]
# decceleration_limits : [1.3,0.0,0.0,0.0,0.0,4.5]
