# for visual odometry and imu fusion

frequency: 10
sensor_timeout: 1.0
two_d_mode: true
transform_time_offset: 0.0
transform_time_out: 0.0
print_diagnostics: true
publish_tf: true
publish_acceleration: false

world_frame: m_map
# map_frame: m_map
odom_frame: m_odom
base_link_frame: base_link

#odom0: wheel odometry
odom0: odom0
odom0_config: [false, false, false,
               false, false, false,
               true, false, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_relative: true

#imu0: imu data
imu0: imu_data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              false, false, false,
              false, false, false]
imu0_differential: true
imu0_relative: false