# gazebo_ros_control/pid_gains:
gains:
  right_rear_wheel_rotate:
    p: 100000.0
    d: 10.0
    i: 0.50
    i_clamp: 3.0

  left_rear_wheel_rotate:
    p: 100000.0
    d: 10.0
    i: 0.50
    i_clamp: 3.0

  # front_wheel_hinge:
  #   p: 100.0
  #   i: 0.01
  #   d: 10.0

  # front_wheel_rotate:
  #   p: 1.0
  #   i: 0.0
  #   d: 0.0
